service: quinn

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10
  region: ${opt:region, 'us-east-2'}
  environment:
    stage: ${opt:stage, 'dev'}
    openai_env: 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

functions:
  hello:
    handler: functions/hello/hello.handler
    layers:
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-requests:9
  init_chat:
    handler: functions/init_chat/init_chat.lambda_handler
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:openai:1
  relay_message:
    handler: functions/relay_message/relay_message.lambda_handler
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:openai:1

plugins:
  - serverless-python-requirements
