service: quinn

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10
  region: ${opt:region, 'us-east-2'}
  iam:
    role: arn:aws:iam::471112961630:role/LambdaRoleWithAccessToOtherServices
  environment:
    stage: ${opt:stage, 'dev'}
    openai_access_key: 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
    WHATSAPP_TOKEN: EAAFpnO7WYJUBOZBF9jlozSBaNkcDvCjJZBmeN6FQGT2ZCATiF5C5ql7hjmeAwhe6ZAO2s77GzSPZBLv5hy9sPjkWvLm3KRb4bZAvujnLKd3rQGGTIzPfZBQyoZAVD2GCGi3UP2lPTdE5afxpquOsssRzJBc7jcrZBzkNHgTzivPIA5dP9SSjuCAw5g93rG0TD3d4Y8FQgb6WTijX7oY8n8DQZD
    VERIFY_TOKEN: QUINN
    openai_organization_id: org-nQnTgti1i8GBtV2AImNwhkCW
    quinn_assistant_id: asst_JGVfvgYliLwfYcBag9inMPcQ
    summarizor_assistant_id: asst_TJTe1fdE8nVj07MNtuylfypi
    anthropic_access_key: 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

functions:
  hello:
    handler: functions/hello/hello.handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-requests:9
  init_chat:
    handler: functions/init_chat/init_chat.lambda_handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-models:1
  relay_message:
    handler: functions/relay_message/relay_message.lambda_handler
    timeout: 30
  whatsapp_entrypoint:
    handler: functions/whatsapp/whatsapp_entrypoint/whatsapp_entrypoint.lambda_handler
    timeout: 30
  whatsapp_token_verifier:
    handler: functions/whatsapp/whatsapp_token_verifier/whatsapp_token_verifier.lambda_handler
    timeout: 30
  whatsapp_conversation_handler:
    handler: functions/whatsapp/whatsapp_conversation_handler/whatsapp_conversation_handler.lambda_handler
    timeout: 30
  summarize_chat:
    handler: functions/summarize_chat/summarize_chat.lambda_handler
    timeout: 30
  filter_message:
    handler: functions/filter_message/filter_message.handler
    timeout: 30
  whatsapp_message_throttler:
    handler: functions/whatsapp_message_throttler/whatsapp_message_throttler.lambda_handler
    timeout: 30
  test_prompt_engineering:
    handler: functions/test/prompt_engineering/prompt_engineering.handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-models:1
  queue_receiver:
    handler: functions/queue_receiver/queue_receiver.lambda_handler
    timeout: 600
    layers:
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-requests:9
  open_ai_assistant_conversation:
    handler: functions/open_ai/assistant_conversation/assistant_conversation.handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-models:1
  open_ai_chat_completion:
    handler: functions/open_ai/chat_completion/chat_completion.handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-models:1
  anthropic_message:
    handler: functions/anthropic/message.handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-models:1

plugins:
  - serverless-python-requirements
