service: quinn

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10
  region: ${opt:region, 'us-east-2'}
  iam:
    role: arn:aws:iam::471112961630:role/LambdaRoleWithAccessToOtherServices
  environment:
    stage: ${opt:stage, 'dev'}
    openai_access_key: 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
    pinecone_access_key: b248c5b4-76ea-46f2-8440-8fdc9886428b
    WHATSAPP_TOKEN: EAAFpnO7WYJUBOZCXYgviE6TCnnvTwRfvniUCa7kGDe6fLkQC71Pa879GSZCd9Rs9xIcuCtEuYjn86wZAYyKK0h8O6Uyn1JSJEZB3iiM8fTH8Kn80ISmRBG43OsRZAUpMZAPNLvfUEhnlerAsq5ShjQhvVAxddW5ZCYMk17wAsjGWSG0hkoOU6gmZBBkhBwXteZC0ybYUAYmriyfqRKEh2HxG7
    VERIFY_TOKEN: QUINN
    openai_organization_id: org-nQnTgti1i8GBtV2AImNwhkCW
    quinn_assistant_id: asst_JGVfvgYliLwfYcBag9inMPcQ
    summarizor_assistant_id: asst_TJTe1fdE8nVj07MNtuylfypi
    anthropic_access_key: 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
    llm: openai
    anthropic_model: claude-3-haiku-20240307
    openai_model: gpt-3.5-turbo
    logger_env: ${opt:env, 'cloud'}

functions:
  process_message:
    handler: lambda_functions/process_message/process_message.lambda_handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-models:2
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-requests:9
  whatsapp_entrypoint:
    handler: lambda_functions/whatsapp/whatsapp_entrypoint/whatsapp_entrypoint.lambda_handler
    timeout: 30
  whatsapp_token_verifier:
    handler: lambda_functions/whatsapp/whatsapp_token_verifier/whatsapp_token_verifier.lambda_handler
    timeout: 30
  whatsapp_conversation_handler:
    handler: lambda_functions/whatsapp/whatsapp_conversation_handler/whatsapp_conversation_handler.lambda_handler
    timeout: 30
  whatsapp_mark_as_read:
    handler: lambda_functions/whatsapp/whatsapp_mark_as_read/whatsapp_mark_as_read.lambda_handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-requests:9
  summarize_chat:
    handler: lambda_functions/summarize_chat/summarize_chat.lambda_handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-models:2
  filter_message:
    handler: lambda_functions/filter_message/filter_message.handler
    timeout: 30
  queue_receiver:
    handler: lambda_functions/queue_receiver/queue_receiver.lambda_handler
    timeout: 600
  rough_canvas_stateless_prompt:
    handler: rough_canvas/prompt_engineering/stateless/stateless_prompt.handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-models:2
  helper_runner:
    handler: helper_functions/helper_runner.handler
    timeout: 30

plugins:
  - serverless-python-requirements
