service: quinn

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10
  region: ${opt:region, 'us-east-2'}
  iam:
    role: arn:aws:iam::471112961630:role/LambdaRoleWithAccessToOtherServices
  environment:
    stage: ${opt:stage, 'dev'}
    openai_access_key: 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
    WHATSAPP_TOKEN: EAAFpnO7WYJUBOZBZCZBNZBOGXlcACGZCfkdmi1lRTZCneNZBJnWUAjVB8FXamIDCrlwjMifRYfVaidx7fDojp6dFBGO0juLsKB0zaG4ZC5rMQLEy6r8FpWeRxGWdymh5uWzZAS4QUgEsyeEjBl5Og3cYaJkkkXNrQshKjjuzByVGrmWeH3kuTontXflDlVLrkKMXG0ZA6vd9O3q6lN6XCIJCUZD
    VERIFY_TOKEN: QUINN
    openai_organization_id: org-nQnTgti1i8GBtV2AImNwhkCW
    quinn_assistant_id: asst_JGVfvgYliLwfYcBag9inMPcQ
    summarizor_assistant_id: asst_TJTe1fdE8nVj07MNtuylfypi
    filteror_assistant_id: asst_8kmEJ4jkBfq7Wj0JnWyjdABl

functions:
  hello:
    handler: functions/hello/hello.handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-requests:9
  init_chat:
    handler: functions/init_chat/init_chat.lambda_handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-openai:1
  relay_message:
    handler: functions/relay_message/relay_message.lambda_handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-openai:1
  whatsapp_entrypoint:
    handler: functions/whatsapp/whatsapp_entrypoint/whatsapp_entrypoint.lambda_handler
    timeout: 30
  whatsapp_token_verifier:
    handler: functions/whatsapp/whatsapp_token_verifier/whatsapp_token_verifier.lambda_handler
    timeout: 30
  whatsapp_conversation_handler:
    handler: functions/whatsapp/whatsapp_conversation_handler/whatsapp_conversation_handler.lambda_handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-requests:9
  summarize_chat:
    handler: functions/summarize_chat/summarize_chat.lambda_handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-openai:1
  filter_message:
    handler: functions/filter_message/filter_message.handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-openai:1
  whatsapp_message_throttler:
    handler: functions/whatsapp_message_throttler/whatsapp_message_throttler.lambda_handler
    timeout: 30
  test_prompt_engineering:
    handler: functions/test/prompt_engineering/prompt_engineering.handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-openai:1

plugins:
  - serverless-python-requirements
