service: quinn

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10
  region: ${opt:region, 'us-east-2'}
  iam:
    role: arn:aws:iam::471112961630:role/LambdaRoleWithAccessToOtherServices
  environment:
    stage: ${opt:stage, 'dev'}
    openai_access_key: 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
    WHATSAPP_TOKEN: EAAFpnO7WYJUBOZCxuArongDHvFFP6yZCmfdFTkhlbrGnqnky3ZBWlR6OQl8lLAUdq3jxGgroEUPUY7ZBWQar6aa5A5CcAZB0Jx1Kt2X323ZATzp2kCpOh8YK1CEh9YQurjTgXQNOGpmQ5rqlRy1aWpJ41iocPcBw3pLTVtcHiZBHfrCvvvVC1rYoDFBnxlnkLn14RIlApOn2mWvWFuxIPelbwZDZD
    VERIFY_TOKEN: QUINN
    openai_organization_id: org-nQnTgti1i8GBtV2AImNwhkCW
    quinn_assistant_id: os.environ.get("quinn_assistant_id")

functions:
  hello:
    handler: functions/hello/hello.handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-requests:9
  init_chat:
    handler: functions/init_chat/init_chat.lambda_handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-openai:1
  relay_message:
    handler: functions/relay_message/relay_message.lambda_handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-openai:1
  whatsapp_entrypoint:
    handler: functions/whatsapp/whatsapp_entrypoint/whatsapp_entrypoint.lambda_handler
    timeout: 30
  whatsapp_token_verifier:
    handler: functions/whatsapp/whatsapp_token_verifier/whatsapp_token_verifier.lambda_handler
    timeout: 30
  whatsapp_conversation_handler:
    handler: functions/whatsapp/whatsapp_conversation_handler/whatsapp_conversation_handler.lambda_handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p310-requests:9
  summarize_chat:
    handler: functions/summarize_chat/summarize_chat.lambda_handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-openai:1
  whatsapp_message_throttler:
    handler: functions/whatsapp_message_throttler/whatsapp_message_throttler.lambda_handler
    timeout: 30
  test_prompt_engineering:
    handler: functions/test/prompt_engineering/prompt_engineering.handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:471112961630:layer:python-openai:1

plugins:
  - serverless-python-requirements
